# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Matrizen" data-toc-modified-id="Matrizen-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Matrizen</a></div><div class="lev2 toc-item"><a href="#Verhältnis-von-Matrizen-und-Vektoren" data-toc-modified-id="Verhältnis-von-Matrizen-und-Vektoren-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Verhältnis von Matrizen und Vektoren</a></div><div class="lev2 toc-item"><a href="#Sonderfälle" data-toc-modified-id="Sonderfälle-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Sonderfälle</a></div><div class="lev2 toc-item"><a href="#Rechenoperationen-für-Matrizen" data-toc-modified-id="Rechenoperationen-für-Matrizen-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Rechenoperationen für Matrizen</a></div><div class="lev3 toc-item"><a href="#Addition-von-Matrizen" data-toc-modified-id="Addition-von-Matrizen-131"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Addition von Matrizen</a></div><div class="lev3 toc-item"><a href="#Multiplikation-mit-einem-Skalar" data-toc-modified-id="Multiplikation-mit-einem-Skalar-132"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Multiplikation mit einem Skalar</a></div><div class="lev3 toc-item"><a href="#Multiplikation-von-Matrizen" data-toc-modified-id="Multiplikation-von-Matrizen-133"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Multiplikation von Matrizen</a></div><div class="lev3 toc-item"><a href="#Die-Inverse-einer-Matrix" data-toc-modified-id="Die-Inverse-einer-Matrix-134"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Die Inverse einer Matrix</a></div><div class="lev3 toc-item"><a href="#Transposition-einer-Matrix" data-toc-modified-id="Transposition-einer-Matrix-135"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Transposition einer Matrix</a></div><div class="lev2 toc-item"><a href="#Rechenregeln-für-Matrizen" data-toc-modified-id="Rechenregeln-für-Matrizen-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Rechenregeln für Matrizen</a></div><div class="lev2 toc-item"><a href="#Matrizen-und-lineare-Gleichungen" data-toc-modified-id="Matrizen-und-lineare-Gleichungen-15"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Matrizen und lineare Gleichungen</a></div><div class="lev1 toc-item"><a href="#Matrizen-in-numpy" data-toc-modified-id="Matrizen-in-numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Matrizen in numpy</a></div><div class="lev2 toc-item"><a href="#Lineare-Gleichungssysteme-lösen" data-toc-modified-id="Lineare-Gleichungssysteme-lösen-21"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Lineare Gleichungssysteme lösen</a></div><div class="lev1 toc-item"><a href="#Literatur" data-toc-modified-id="Literatur-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Literatur</a></div>

# Matrizen

Eine Matrix ist eine Anordnung von Einzelwerten in Spalten und Zeilen. Die folgende Matrix hat 4 Zeilen und 3 Spalten: 

$$
A = \begin{pmatrix} 2 & 7 & 9\\
11 & 1 & 4\\
4 & 12 & 1\\
1 & 2 & 2
\end{pmatrix}
$$

Die 'Zellen' einer Matrix werden über die Zeilen/Spalten-Koordinaten angegeben. In allen Fällen wird immer zuerst die Zeile, dann die Spalte genannt. Allgemein kann man also jede Matrix mit m Zeilen und n Spalten so beschreiben:

$$
A = \begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
 a_{21} & a_{22} & \cdots & a_{2n}\\
 \vdots & \vdots & \vdots & \vdots\\
 a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix}
$$
m x n sind die <b>Dimensionen</b> der Matrix.

## Verhältnis von Matrizen und Vektoren
Vektoren können als eindimensionale Matrizen verstanden werden. Das hier ist eine Reihenvektor:

$$
A = \begin{pmatrix} 2 & 7 & 9\end{pmatrix}
$$

Normalerweise werden Vektoren jedoch als Spaltenvektoren aufgefasst, also so:

$$
A = \begin{pmatrix} 2 \\ 7 \\ 9\end{pmatrix}
$$

## Sonderfälle
Es gibt zwei Sonderfälle von Matrizen, die häufig auftreten:
Die <b>quadratische Matrix</b>, die ebensoviele Spalten wie Zeilen hat:
$$
A = \begin{pmatrix} 2 & 7 & 9\\
11 & 1 & 4\\
4 & 12 & 1
\end{pmatrix}
$$

Die Elemente der Diagonalen von Linksoben nach Rechtsunten werden als Diagonalelemmente oder <b>Haupt-Diagonale</b> bezeichnet. 

Sowie die <b>Nullmatrix</b>:
$$
0 = \begin{pmatrix} 0 & 0  & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{pmatrix}
$$


<b>Obere Dreiecksmatrix</b>
Eine obere Dreiecksmatrix ist eine quadratische Matrix, deren linke untere Hälfte aus Nullen besteht:
$$
A = \begin{pmatrix}a_{11} & a_{12} & \cdots & a_{1n} \\ 
0 & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn} \\
\end{pmatrix}
$$

<b>Untere  Dreiecksmatrix</b>

Eine untere Dreiecksmatrix ist eine quadratische Matrix, deren rechte obere Hälfte aus Nullen besteht:
$$
A = \begin{pmatrix}a_{11} & 0 & \cdots & 0 \\ 
a_{21} & a_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn} \\
\end{pmatrix}
$$


<b>Diagonalmatrix</b>
Eine quadratische Matrix bei der alle Elemente 0 sind und nur die Hauptdiagonale Werte ungleich 0 hat, nennt man eine Diagonalmatrix. 

$$
A = \begin{pmatrix} a_{11}& 0 & \cdots  & 0\\
                       0 & a_{22} & \cdots & 0\\
                    \vdots & \vdots & \ddots & \vdots\\
                    0 & 0 & 0 & a_{nn}
\end{pmatrix}
$$

<b>Einheitsmatrix</b>
Diese Matrix ist ein Sonderfall der Diagonalmatrix. Die Werte der Diagonale sind alle 1. 
$$
\mathbb{I} = \begin{pmatrix} 1& 0 & \cdots  & 0\\
                       0 & 1 & \cdots & 0\\
                    \vdots & \vdots & \ddots & \vdots\\
                    0 & 0 & 0 & 1
\end{pmatrix}
$$


## Rechenoperationen für Matrizen

### Addition von Matrizen
Definiert ist nur die Addition von Matrizen mit der gleichen Dimension. Die Summe ist eine neue Matrix mit der gleichen Dimension, wobei die Elemente der Summe durch die Summe der Elemente in den Ausgangsmatrizen bestimmt werden Wenn wir also die Matrix A und die Matrix B addieren, dann werden die Elemente in der Summe C so berechnet:  $$ c_{11} = a_{11} + b_{11}$$ 
$$ c_{12} = a_{12} + b_{12}$$ 
usw. 

Hier ein Beispiel:
$$
A = \begin{pmatrix}2 & 4 & 11\\
3 & 2 & 4
\end{pmatrix}
$$
$$
B = \begin{pmatrix}3 & 7 & 2\\
3 & 1 & 5
\end{pmatrix}
$$
$$
A + B = \begin{pmatrix}5 & 11 & 13\\
6 & 3 & 9
\end{pmatrix}
$$




### Multiplikation mit einem Skalar
Auch die Multiplikation mit einem Skalar funktioniert so, wie wir es bereits von der Vektoralgebra kennengelernt haben. Jedes Element der Matrix wird mit dem Skalar multipliziert: 

Beispiel:

$$
A = \begin{pmatrix}2 & 4\\7 & 3\end{pmatrix}
$$

$$ 
k A = k \begin{pmatrix}2 & 4\\7 & 3\end{pmatrix} = \begin{pmatrix} 2k & 4k\\7k & 3k\end{pmatrix}
$$


### Multiplikation von Matrizen
Die meisten Rechenregeln, die man so kennt, sind kommutativ, z.B. im Fall der Addition: 

    a + b = b + a

Das gilt nicht für die Multiplikation von Matrizen. 
$$
A * B \neq B * A
$$

Die Multiplikation zweier Matrizen A und B ist nur definiert, wenn die Anzahl der Spalten von A mit der Anzahl der Zeilen von B übereinstimmt. Wenn also A die Dimension m,n hat muss B die Dimension n, r haben. Das Ergebnis ist eine neue Matrix C, die die Dimension m, r hat. Zur Berechnung der Elemente von C gilt:

$$
c_{ij} = \sum_{k=1}^n{a_{ik}b_{kj}} = a_{i1}b_{1j} + a_{i2}b_{2j} + \cdots + a_{in}b_{nj}
$$

Nehmen wir den einfachen Fall dim(A) = (3,2)
$$
A = \begin{pmatrix}3 & 5\\7 & 1\\9 & 2\end{pmatrix}
$$
und dim B(2,3)
$$
B = \begin{pmatrix}1 & 2 & 1\\5 & 6 & 2\end{pmatrix}
$$

dann ist dim(C) = (3,3)

Und das Ergebnis ist: 


Die einfachste Möglichkeit, die Matrixmultiplikation systematisch abzuarbeiten, ist Anwendung des Falk'schen Schemas. Es ordnet die Matrix A und B so an, dass evident ist, welche Elemente welcher Matrix multipliziert werden müssen:



$$
\begin{equation*}
\begin{array}{@{}rl}
    {B} \ = \
    \left(
    \begin{array}{c} b_{11} \\ \vdots \\ b_{p1}
          \end{array}
    \begin{array}{c} \cdots \\   \\ \cdots \end{array}
\fbox{$\begin{array}{c} b_{1k} \\ \vdots \\ b_{pk}
    \end{array}$}
    \begin{array}{c} \cdots \\   \\ \cdots \end{array}
    \begin{array}{c} b_{1n} \\ \vdots \\ b_{pn}
          \end{array}
    \right) \, &
\\
    {A} \ = \
    \left(
    \begin{array}{c}
        a_{11} \quad \cdots \quad a_{1p} \\
        \ \vdots \hfill \vdots \quad  \\
        \fbox{$a_{i1} \quad \cdots \quad a_{ip}$} \\
        \ \vdots \hfill \vdots \quad \\
        a_{m1} \quad \cdots \quad a_{mp}
    \end{array} \right) \
    \left(
    \begin{array}{c} c_{11} \\ \vdots \\ c_{i1} \\
        \vdots \\ c_{m1}          \end{array}
    \begin{array}{c} \cdots \\   \\ \cdots \\ \\ \cdots \end{array}
        \begin{array}{c} c_{1k} \\ \vdots \\ \fbox{$c_{ik}$} \\
            \vdots \\ c_{mk}
    \end{array}
    \begin{array}{c} \cdots \\   \\ \cdots \\ \\ \cdots \end{array}
    \begin{array}{c} c_{1n} \\ \vdots \\ c_{in} \\
        \vdots \\ c_{mn}          \end{array}
    \right) &  = \ {C}
\end{array}
\end{equation*}$$





Führen wir das an unserem einfachen Beispiel von oben durch:

$$
A = \begin{pmatrix}3 & 5\\7 & 1\\9 & 2\end{pmatrix}
$$
und dim B(2,3)
$$
B = \begin{pmatrix}1 & 2 & 1\\5 & 6 & 2\end{pmatrix}
$$

Wenn wir das Falk'sche Schema anwenden, ergibt sich folgendes Bild. Links sehen wir das Schema einschließlich des Ergebnisses und rechts, wie eine einzelne Zelle des Ergebnisses  berechnet wird.

<img src="images\matrix_mp.png"/>



### Die Inverse einer Matrix


Wie wir gesehen haben, kann man mit Matrizen die gleichen Operationen durchführen kann wie z.B. mit reelen Zahlen: Addition (einschließlich der  Subtraktion) und Multiplikation. Wie sieht es mit der Division aus? Die spezifischen Rechenregeln der Multiplikation legen es schon nahe, dass die Division ein Sonderfall ist. Wenn wir mit reelen Arbeiten, dann entspricht die Division durch x der Multiplikation mit dem Kehrwert von x:

$$
a:x = a \frac{1}{x}
$$

Der Kehrwert von x ist dadurch gekennzeichnet, dass gilt:

$$
x \cdot \frac{1}{x} = 1
$$

Stellt sich also erst einmal die Frage, ob für eine Matrix A eine andere Matrix existiert, mit der sie multipliziert das Matrix-Äquivalent zur 1 ergibt. Die 1 hat ja die Eigenschaft:

$$
 1 \cdot a = a
$$


Entsprechend muss gelten:

$$
X \cdot A = A
$$

Dieses X ist die Einheitsmatrix mit der passenden Dimension:

$$
A \cdot \mathbb{I}_n = \mathbb{I}_m \cdot A = A
$$

Zurück zur 'Division'. Das bedeutet also, wir suchen eine Matrix, für die gilt:

$$
A \cdot X = \mathbb{I}
$$

Eine quadratische Matrix, die diese Bedingung in Bezug auf A erfüllt, nennt man die <b>Inverse</b> zu A. Sie wird üblicherweise so geschrieben: 

$$
A \cdot A^{-1} = \mathbb{I}
$$

Nicht jede quadratische Matrix hat eine Inverse. Diejenigen Matrizen, die eine Inverse haben, nennt man <b>reguläre</b> Matrizen; Matrizen, die keine Inverse haben, nennt man <b>singulär</b>.

Wie ermittelt man, ob eine quadratische Matrix invertierbar ist? 

Wir wissen:

$$
A \cdot A^{-1} = \mathbb{I}
$$


Wenn A die Dimension (2,2) hat, dann gilt:

$$
\begin{pmatrix}a_{11} & a_{12}\\a_{21} & a_{22}\end{pmatrix} \cdot \begin{pmatrix}x_{11} & x_{12}\\x_{21} & x_{22}\end{pmatrix} = \begin{pmatrix}1 & 0\\0 & 1\end{pmatrix}   
$$

Multipliziert man die Matrizen aus, dann ergeben sich folgende Gleichungen:




$$
a_{11}x_{11} + a_{12}x_{21} = 1 
$$
$$
a_{21}x_{11} + a_{22}x_{21} = 0 
$$
$$
a_{11}x_{12} + a_{12}x_{12} = 1 
$$
$$
a_{21}x_{12} + a_{22}x_{22} = 0 
$$

Wir werden später bessere und schnellere Methoden zur Berechnung von Inversen kennenlernen

### Transposition einer Matrix
Schon aus praktischen Gründen spielt die Operation der Transposition eine wichtige Rolle: Sie macht aus den Spalten einer Matrix deren Zeilen und umgekehrt aus den Zeilen einer Matrix deren Spalten. Wenn man also etwa eine Term-Dokument-Matrix hat, d.h. eine Matrix, deren Zeilen jeweils einem Wort zugeordnet sind und deren Spalten jeweils ein Dokument repräsentieren, dann hat man nach der Transposition eine Dokument-Term-Matrix, in der jede Zeile die Häufigkeiten der Worte in einem Dokument anzeigt, während die Spalten nun jeweils die Häufigkeiten eines bestimmten Wortes anzeigen.
Wenn 
$
A = \begin{pmatrix}3 & 7 & 4 & 6 \\
                   7 & 2 & 1 & 9
\end{pmatrix}
$

dann ist 

$
A^T = \begin{pmatrix}3 & 7 \\
                   7 & 2\\
                   4 & 1\\
                   6 & 9
\end{pmatrix}
$

Eine <b>symmetrische</b> Matrix ist eine Matrix für die gilt A = A<sup>T</sup>.

Folgende Rechenregeln können den Umgang mit transponierten Matrizen erleichtern:

$
(A + B)^T = A^T + B^T
$

$
(kA)^T = kA^T
$

$
(A^T)^T = A
$



## Rechenregeln für Matrizen
Da alle Matrizen mit der Dimension (m,n) einen Vektorraum bilden, gilt Folgendes:
    
A + B = B + A (Kommutativität)

A + (B + c) = (A + B) + C (Assoziativität)

A + <b>0</b> = A

A + (-A) = <b>0</b>

k(hA) = kh(A)

1A = A

k(A + B)  = kA + kB (Distributivität)

(k + h) A = kA + hA (Distributivität)

Die Dimension des Vektorraums ist (m,n)

Wichtig: 
Die Operation A * B verändert die Dimension: wenn dim(A) = (m, n) und dim(B) = (n, r), dann ist dim(A*B) = (m, r). Vor allem aber gilt: 
$$
A * B \neq  B * A
$$


## Matrizen und lineare Gleichungen

Ein lineares Gleichungssystem aus m Gleichungen mit n Unbekannten
x1, x2, . . . , xn hat die Form

$$
a_{11}x_1 + a_{12}x_2 + · · · + a_{1n}x_n = b_1
$$
$$
a_{21}x_1 + a_{22}x_2 + · · · + a_{2n}x_n = b_2
$$
$$
\cdots
$$
$$
a_{m1}x_1 + a_ {m2}x_2 + · · · + a_{mn}x_n = b_m
$$

a<sub>ij</sub> nennt man die Koeffizienten des Gleichungssystems. Sind alle b<sub>i</sub> gleich null, so heißt das
Gleichungssystem <b>homogen</b>, andernfalls <b>inhomogen</b>.

Ein inhomogenes lineares Gleichungssystem über  $K =\mathbb{R}$ hat keine, genau eine oder unendlich viele Lösungen.
Ein homogenes lineares Gleichungssystem hat immer zumindest eine (die sogenannte 'triviale') Lösung, nämlich x1 = x2 = . . . = xn = 0. 


Wir können ein solches Gleichungssystem in Form einer erweiteren Koeffizientenmatrix notieren:
$$
A = 
\left(
\begin{array}{c c c c | c}
a_{11}x_1 & a_{12}x_2 & \cdots & a_{1n}x_n  & b_1 \\
a_{21}x_1 & a_{22}x_2 & \cdots & a_{2n}x_n  &  b_2 \\
\vdots   & \vdots     &  \vdots & \vdots & \vdots \\
a_{m1}x_1 & a_ {m2}x_2 & · · · & a_{mn}x_n &  b_m\\
\end{array}
\right)
$$

Wir können ein solches Gleichungssystem umformen, indem wir eine dieser <b>Zeilenumformungen</b> anwenden:

* Vertauschen von zwei Zeilen
* Multiplikation einer Zeile mit einer Zahl $\lambda$ (wobei $\lambda \ne 0$ und $\lambda \in \mathbb{R}$ )
* Addition des $\lambda$-fachen einer Zeile zu einer anderen Zeile 

Eine Matrix ist in <b>Zeilenstufenform</b>, wenn
* Zeilen, die nur Nullen enthalten, in den unter Zeilen der umgeformten Matrix stehen
* das erste Element in jeder Zeile eine 1 ist
* die führende 1 in jeder Zeile rechts von der führenden 1 darüber steht

Die Anzahl der Zeilen, die nicht aus Nullen bestehen, nennt man den <b>Rang</b> der Matrix. Diese Zeilen enthalten alle Informationen zum Lösen der Matrix. 

Eine Matrix ist in <b>reduzierter Zeilenstufenform</b>, wenn außerdem
* über jeder führenden 1 Nullen stehen


# Matrizen in numpy

Matrizen kann man mit der Methode matrix anlegen. Die Werte können einfach mit Leerzeichen getrennt in eine Zeile geschrieben werden. Ein Semikolon markiert eine neue Zeile. 

In [2]:
import numpy as np
A = np.matrix('2, 5, 12 4; 3, 7, 2, 5; 1, 3, 11, 1')
A

matrix([[ 2,  5, 12,  4],
        [ 3,  7,  2,  5],
        [ 1,  3, 11,  1]])

Anzeige der Dimension leider nicht mit 'dim', sondern mit dem Attribut 'shape':

In [3]:
A.shape

(3, 4)

Man kann in numpy sehr einfach einer Matrix eine neue Dimension zuweisen, auch wenn das nur unter sehr bestimmten Bedingungen eine sinnvolle Operation ist.

In [4]:
A.reshape (6, 2)

matrix([[ 2,  5],
        [12,  4],
        [ 3,  7],
        [ 2,  5],
        [ 1,  3],
        [11,  1]])

Das Rechnen mit Matrizen funktioniert fast genau so, wie man es erwarten würde: 

In [5]:
A

matrix([[ 2,  5, 12,  4],
        [ 3,  7,  2,  5],
        [ 1,  3, 11,  1]])

In [6]:
B = np.matrix('3, 2, 1, 0; 6, 5, 4, 3; 9, 8, 7, 6')
B

matrix([[3, 2, 1, 0],
        [6, 5, 4, 3],
        [9, 8, 7, 6]])

Addition von Matrizen:

In [7]:
A + B

matrix([[ 5,  7, 13,  4],
        [ 9, 12,  6,  8],
        [10, 11, 18,  7]])

Multiplikation mit einem Skalar:

In [8]:
3 * A

matrix([[ 6, 15, 36, 12],
        [ 9, 21,  6, 15],
        [ 3,  9, 33,  3]])

In [9]:
B = B.reshape(4, 3)
B

matrix([[3, 2, 1],
        [0, 6, 5],
        [4, 3, 9],
        [8, 7, 6]])

Multiplikation der Matrizen A (3, 4) und B (4, 3). Die neue Matrix hat die Dimension (3,3) 

In [10]:
A * B

matrix([[ 86,  98, 159],
        [ 57,  89,  86],
        [ 55,  60, 121]])

Einfaches Beispiel von oben:

In [11]:
A = np.matrix('3 5;7 1;9 2')
B = np.matrix('1  2  1; 5 6 2')
A * B

matrix([[28, 36, 13],
        [12, 20,  9],
        [19, 30, 13]])

Inverse einer Matrix berechnen:

In [12]:
X = np.matrix('3 5;7 1')
X

matrix([[3, 5],
        [7, 1]])

In [13]:
Xinv = np.linalg.inv(X)
Xinv

matrix([[-0.03125,  0.15625],
        [ 0.21875, -0.09375]])

In [14]:
#Matrix mal Inverse ergeben die Einheitsmatrix
X * Xinv

matrix([[ 1.,  0.],
        [ 0.,  1.]])

## Lineare Gleichungssysteme lösen

Wenn wir ein Gleichungssystem als Matrix-Vektor-Multiplikation schreiben, also A eine Matrix ist, x ein Vektor mit den unbekannten x<sub>1</sub> bis x<sub>n</sub> und b der Lösungsvektor, so dass gilt:
$$
Ax = b
$$
dann kann man die Werte von x mit numpy so berechnen:

```Python
np.linalg.solve(A, b)
```
Ein Beispiel:

In [15]:
A = np.matrix('2 3 -1;-1 1 1;5 3 -9')
print("A = \n", A)
b = np.array([34, 6, 38])
x = np.linalg.solve(A, b)
print("x = ", x)

A = 
 [[ 2  3 -1]
 [-1  1  1]
 [ 5  3 -9]]
x =  [ 4.  9.  1.]


Den Rang einer Matrix kann man mit `np.linalg.matrix_rank`  ermitteln:

In [16]:
np.linalg.matrix_rank(A)

3

In [17]:
import sympy
sympy.Matrix(A).rref()

(Matrix([
 [1.0,   0,   0],
 [  0, 1.0,   0],
 [  0,   0, 1.0]]), [0, 1, 2])

# Literatur

* Gerald und Susanne Teschl: Mathematik für Informatiker Bd.: 1: Diskrete Mathematik und lineare Algebra. Heidelberg: Springer 2011. (Kap. 9-14)
* Tilo Arens et al.: Mathematik. 3. Aufl. Heidelberg: Springer 2015. (Teil III: Lineare Algebra)
* Michael Ruhrländer: Lineare Algebra für Naturwissenschaftler und Ingenieure. Hallbergmoos: München 2017. 